name: Preprocess external workflow

on: push

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Checkout external repo
        uses: actions/checkout@v4
        with:
          repository: Jack6131/testingkeys
          path: external

      - name: Install yq
        run: sudo apt-get update && sudo apt-get install -y yq

      - name: Preprocess external workflow
        run: |
          echo "::group::Preprocessed workflow"
          yq eval '.jobs.build.runs-on = "ubuntu-latest"' \
          external/.github/workflows/blank.yml
          echo "::endgroup::"
